server:
  port: 8083

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/client
    username: ${DB-USERNAME}
    password: ${DB-PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: localhost
    port: 15672
    username: ${RABBIT-USERNAME}
    password: ${RABBIT-PASSWORD}
